
@baseURL = http://127.0.0.1:8000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJheXVzaEAxMjM0LmNvbSIsImV4cCI6MTc4NDAyNzY5OX0.YZ4q4cStCdwLiDWT5HxF1hDNHfXxHsgahg3wL1_Ee3U

GET {{baseURL}}/health

###
POST {{baseURL}}/auth/register
Content-Type: application/json

{
    "name": "Ayush Rai",
    "email": "ayush@1234.com",
    "password": "1234"
}

###
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "ayush@1234.com",
    "password": "1234"
}

###

GET {{baseURL}}/auth/me
Authorization: Bearer {{access_token}}

###

GET {{baseURL}}/employees/
Authorization: Bearer {{access_token}}

###

GET {{baseURL}}/employees/1
Authorization: Bearer {{access_token}}

###

POST {{baseURL}}/employees
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "age": 26,
    "designation": "SDE Intern"
}
